<a href="https://colab.research.google.com/github/julianovale/Python_DS_-_ML/blob/main/0002_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre por que você deseja usar Arrays em vez de listas, confira esta excelente publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Nós só aprenderemos os conceitos básicos do NumPy, para começar, precisamos instalá-lo!

## Instruções de instalação

** É altamente recomendável que instale o Python usando a distribuição da Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de Álgebra Linear) se sincronizem com o uso de uma instalação conda. Se você tiver o Anaconda, instale o NumPy acessando seu terminal ou prompt de comando e digite: **

    conda install numpy
    
** Se você não possui Anaconda e não pode instalá-lo, consulte: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

Numpy possui muitas funções e capacidades incorporadas. Não vamos cobri-los na totalidade, mas, em vez disso, vamos nos concentrar em alguns dos aspectos mais importantes de Numpy: vetores, arrays, matrizes e geração de números. Comecemos por arrays:

# Numpy Arrays

As matrizes de NumPy são a maneira principal de usar Numpy ao longo do curso. Numpy arrays essencialmente vêm de duas formas: vetores e matrizes. Os vetores são estritamente arranjos de 1d e as matrizes são 2d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [15]:
np.random.rand(2)

array([0.21176849, 0.8912575 ])

In [16]:
np.random.rand(5,5)

array([[0.46361535, 0.90661566, 0.86728897, 0.10261997, 0.35138902],
       [0.46671614, 0.36557595, 0.67767661, 0.23410424, 0.14363042],
       [0.96651362, 0.10834455, 0.12748876, 0.45396316, 0.34777567],
       [0.22792924, 0.88324653, 0.01181307, 0.60340648, 0.55366193],
       [0.05878117, 0.20719212, 0.94599938, 0.87008053, 0.48190117]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [17]:
np.random.randn(2)

array([-1.44130439, -0.09846069])

In [18]:
np.random.randn(5,5)

array([[-0.060658  ,  0.47826746,  0.54262711, -0.27337616,  2.00345324],
       [ 0.02458578,  0.17722377,  2.18096399, -1.11295469, -1.34876251],
       [ 0.75610729, -0.08410233,  1.27465386, -0.57809667,  0.80216107],
       [ 0.35324608,  0.72355273,  0.63088148, -2.30833299, -0.65181681],
       [ 1.95147673, -0.47298794, -1.11136914, -0.17840128,  0.98069141]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [19]:
np.random.randint(1,100)

58

In [20]:
np.random.randint(1,100,10)

array([12, 71, 87, 30, 44, 75, 99, 25, 18, 14])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([45, 35, 20, 13, 39, 26, 10, 28, 17, 39])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [25]:
ranarr

array([45, 35, 20, 13, 39, 26, 10, 28, 17, 39])

In [26]:
ranarr.max()

45

In [27]:
ranarr.argmax()

0

In [28]:
ranarr.min()

10

In [29]:
ranarr.argmin()

6

## Shape

Shape é um atributo que os arrays têm (não um método):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [35]:
arr.dtype

dtype('int64')