<a href="https://colab.research.google.com/github/julianovale/Python_DS_-_ML/blob/main/0003_Indexa%C3%A7%C3%A3o_de_Numpys_e_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexação de Numpys e Arrays

Nesta palestra, vamos discutir como selecionar elementos ou grupos de elementos de uma matriz.

In [1]:
import numpy as np

In [2]:
# Criando um simples array
arr = np.arange(0,11)

In [3]:
# Mostrar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexação e seleção
A maneira mais simples de escolher um ou alguns elementos de uma matriz é muito semelhante às listas de python:

In [4]:
# Obtendo um valor através de um índice
arr[8]

8

In [5]:
# Obtendo valores em um intervalo
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Transmissão

Numpy arrays diferem de uma lista Python normal por causa de sua capacidade de transmissão:

In [7]:
# Configurando um valor com intervalo de índice (Transmissão)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Redefinir matriz, veremos por que eu tive que redefinir em um momento
arr = np.arange(0,11)

# Mostrando
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Notas importantes sobre fatias
slice_de_arr = arr[0:6]

# Mostra a fatia
slice_de_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
# Modifica a fatia
slice_de_arr[:]=99

#Show Slice again
slice_de_arr

array([99, 99, 99, 99, 99, 99])

Agora note que as mudanças também ocorrem em nossa matriz original!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Os dados não são copiados, é uma visão da matriz original! Isso evita problemas de memória!

In [12]:
# Para obter uma cópia, precisa ser explícito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexando uma matriz 2D

O formato geral é ** arr_2d [row] [col] ** ou ** arr_2d [row, col] **. Eu recomendo geralmente usando a notação de vírgula para maior clareza.

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Mostrando
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
# Fila de indexação
arr_2d[1]


array([20, 25, 30])

In [15]:
# O formato é arr_2d [row] [col] ou arr_2d [row, col]

# Obtendo o valor do elemento individual
arr_2d[1][0]

20

In [16]:
# Obtendo o valor do elemento individual
arr_2d[1,0]

20

In [17]:
# Fatiando um array 2D

# Fatia (2,2) do canto superior direito
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
# Fatia inferior
arr_2d[2]

array([35, 40, 45])

In [19]:
# Fatia inferior
arr_2d[2,:]

array([35, 40, 45])

### Indexação "Fancy"

A indxação "Fancy" permite que você selecione linhas inteiras ou colunas fora de ordem, para mostrar isso, vamos construir rapidamente uma matriz numpy:

In [20]:
arr2d = np.zeros((10,10))

In [21]:
# Tamaho do array
arr_length = arr2d.shape[1]

In [22]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Indexação "Fancy" permite o seguinte:

In [23]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [24]:
# Permite em qualquer ordem
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Mais Ajuda de Indexação
A indexação de uma matriz 2d pode ser um pouco confusa no início, especialmente quando você começa a adicionar em tamanho de etapa. Experimente pesquisar no Google "indexação NumPy" para imagens úteis, como esta:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Seleção

Vamos examinar brevemente como usar colchetes para seleção com base em operadores de comparação.

In [25]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [27]:
bool_arr = arr>4

In [28]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])